### ISSUE TITLE
Incompatible with Meteor 1.3

### ISSUE THREAD

**Issue by xcv58** [auth0/meteor-auth0#15]
It cannot be compiled in Meteor 1.3 with error message: `binding arguments in strict mode`

It's because you cannot use Arguments as an identifier, refer https://msdn.microsoft.com/en-us/library/br230269(v=vs.94).aspx

The actual code line:
```javascript
    function _addAccountsCallback(arguments) {
    }
```
https://github.com/auth0/meteor-auth0/blob/bd7821d65ec53c3ce5c291a3b2ab5d24c09a13ef/lock/auth0-lock.js#L63

**Comment by spawn-guy** [comment]
@xcv58 thank you for `Meteor.lock`. Also your package - actually Works!

**Comment by xcv58** [comment]
@spawn-guy No problem. I'll mark my package deprecated when the Auth0 team update its package.

**Comment by xcv58** [comment]
Fixed, use my forked package as temporary solution: https://atmospherejs.com/xcv58/auth0-lock

**Comment by jdheeter** [comment]
Thanks for forking your package. Can someone explain how to import lock from the Auth0 package? When I call meteor.lock.show() I get a "show is not a method of undefined" type error.

**Comment by xcv58** [comment]
@jdheeter I'll update the sample soon, please make sure you use the `xcv58:auth0-lock@ 0.4.1`.

**Comment by xcv58** [comment]
@jdheeter Please check this https://github.com/xcv58/meteor-auth0/tree/1.3/examples/sample-app

And you may need to change your `settings.json` accordingly, please refer: https://github.com/xcv58/meteor-auth0/blob/1.3/examples/sample-app/settings.json

One more thing, you should use the `xcv58:auth0-lock@6.0.2`.

The API of `Lock` has changed a little bit. Please review this https://github.com/auth0/lock/tree/v10 if you have any issue.
